Repository algolia/instantsearch, pull requests merged in 2020-03, with the labels that each got.

#4344 fix(refinementList): prevent XSS via routing
  src/components/RefinementList/RefinementList.js
  src/components/RefinementList/__tests__/RefinementList-test.js
  src/widgets/refinement-list/__tests__/__snapshots__/refinement-list-test.js.snap
  src/widgets/refinement-list/defaultTemplates.js
Labels: Type: Bug

#4347 chore(favours-types): replaces interfaces by types
  examples/e-commerce/src/routing.ts
  src/components/Panel/Panel.tsx
  src/connectors/autocomplete/connectAutocomplete.ts
  src/connectors/configure-related-items/connectConfigureRelatedItems.ts
  src/connectors/configure/connectConfigure.ts
  src/connectors/current-refinements/connectCurrentRefinements.ts
  src/connectors/infinite-hits/connectInfiniteHits.ts
  src/connectors/numeric-menu/connectNumericMenu.ts
  src/connectors/query-rules/connectQueryRules.ts
  src/connectors/voice-search/connectVoiceSearch.ts
  src/lib/createHelpers.ts
  src/lib/suit.ts
  src/lib/utils/getRefinements.ts
  src/middleware/createRouter.ts
  src/middleware/index.ts
  src/types/algoliasearch.ts
  src/types/instantsearch.ts
  src/types/widget.ts
  src/widgets/current-refinements/current-refinements.tsx
  src/widgets/infinite-hits/infinite-hits.tsx
  src/widgets/panel/panel.tsx
  src/widgets/places/places.ts
  src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
  src/widgets/voice-search/__tests__/voice-search-test.ts
  src/widgets/voice-search/voice-search.tsx
Labels: Type: Enhancement

#4350 chore(ts-migration): hits per page rename files
  src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.ts
  src/connectors/hits-per-page/connectHitsPerPage.ts
  src/widgets/hits-per-page/__tests__/hits-per-page-test.ts
  src/widgets/hits-per-page/hits-per-page.tsx
  stories/hits-per-page.stories.ts
Labels: Status: ⚠️ DO NOT MERGE

#4351 chore(ts-migration): hits per page connector and widget
  src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.ts
  src/connectors/hits-per-page/connectHitsPerPage.ts
  src/widgets/hits-per-page/__tests__/__snapshots__/hits-per-page-test.ts.snap
  src/widgets/hits-per-page/__tests__/hits-per-page-test.ts
  src/widgets/hits-per-page/hits-per-page.tsx
  stories/hits-per-page.stories.ts
Labels: Scope: TypeScript, Status: ⚠️ DO NOT MERGE

#4362 feat: introduce controlled mode
  package.json
  src/lib/InstantSearch.ts
  src/lib/__tests__/InstantSearch-test.js
  src/lib/utils/checkIndexUiState.ts
  src/lib/utils/index.ts
  src/middleware/createRouter.ts
  src/middleware/index.ts
  src/widgets/index/__tests__/index-test.ts
  src/widgets/index/index.ts
  test/mock/createInstantSearch.ts
Labels: Scope: Core, Type: Feature

#4361 chore(ts-migration): refactors connector types
  src/connectors/autocomplete/connectAutocomplete.ts
  src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test.ts
  src/connectors/configure-related-items/connectConfigureRelatedItems.ts
  src/connectors/configure/__tests__/connectConfigure-test.ts
  src/connectors/configure/connectConfigure.ts
  src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
  src/connectors/current-refinements/connectCurrentRefinements.ts
  src/connectors/hits-per-page/connectHitsPerPage.ts
  src/connectors/infinite-hits/connectInfiniteHits.ts
  src/connectors/numeric-menu/connectNumericMenu.ts
  src/connectors/query-rules/__tests__/connectQueryRules-test.ts
  src/connectors/query-rules/connectQueryRules.ts
  src/connectors/voice-search/connectVoiceSearch.ts
  src/lib/__tests__/insights-client-test.ts
  src/lib/insights/client.ts
  src/lib/utils/checkRendering.ts
  src/types/connector.ts
  src/types/widget.ts
  src/widgets/configure-related-items/configure-related-items.ts
  src/widgets/configure/configure.ts
  src/widgets/current-refinements/current-refinements.tsx
  src/widgets/hits-per-page/hits-per-page.tsx
  src/widgets/infinite-hits/infinite-hits.tsx
  src/widgets/panel/panel.tsx
  src/widgets/places/places.ts
  src/widgets/query-rule-context/query-rule-context.tsx
  src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
  src/widgets/voice-search/voice-search.tsx
Labels: Scope: TypeScript, Status: ⚠️ DO NOT MERGE

#4364 chore(ts-migration): adds api extractor for type definitions
  CONTRIBUTING.md
  api-extractor.json
  package.json
  scripts/build/types.js
  scripts/release/build-experimental-typescript.js
  ship.config.js
  yarn.lock
Labels: Scope: TypeScript, Status: ⚠️ DO NOT MERGE

#4365 chore(fixes-yarn-lint-hangs): adds ecommerce example to eslintignore
  .eslintignore
Labels: Scope: Tooling
